import { supabase } from "@/integrations/supabase/client";

/**
 * Chat API functions
 */

export interface ChatConversation {
  id: string;
  user_id: string;
  user_name: string;
  user_email: string;
  topic: string;
  status: 'active' | 'closed';
  created_at: string;
  closed_at: string | null;
}

export interface ChatMessage {
  id: string;
  conversation_id: string;
  sender_type: 'user' | 'agent' | 'system';
  sender_name: string;
  message: string;
  created_at: string;
  is_read: boolean;
}

export interface SupportTicket {
  id: string;
  ticket_number: string;
  user_id: string | null;
  user_name: string;
  user_email: string;
  topic: string;
  message: string;
  status: 'open' | 'in_progress' | 'resolved' | 'closed';
  created_at: string;
  updated_at: string;
}

/**
 * Create a new chat conversation
 */
export const createConversation = async (data: {
  user_name: string;
  user_email: string;
  topic: string;
}) => {
  try {
    console.log('💬 Creating conversation');
    
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data: conversation, error } = await supabase
      .from('chat_conversations')
      .insert([{
        user_id: user?.id || '00000000-0000-0000-0000-000000000000',
        user_name: data.user_name,
        user_email: data.user_email,
        topic: data.topic,
        status: 'active',
      }])
      .select()
      .single();

    if (error) throw error;

    // Create welcome message
    await supabase
      .from('chat_messages')
      .insert([{
        conversation_id: conversation.id,
        sender_type: 'system',
        sender_name: 'System',
        message: `Welcome ${data.user_name}! We'll connect you with a support agent shortly.`,
      }]);

    console.log('✅ Conversation created:', conversation.id);
    return conversation;
  } catch (error) {
    console.error('❌ Failed to create conversation:', error);
    throw error;
  }
};

/**
 * Get conversation messages
 */
export const getConversationMessages = async (conversationId: string) => {
  try {
    const { data, error } = await supabase
      .from('chat_messages')
      .select('*')
      .eq('conversation_id', conversationId)
      .order('created_at', { ascending: true });

    if (error) throw error;
    return data || [];
  } catch (error) {
    console.error('❌ Failed to get messages:', error);
    throw error;
  }
};

/**
 * Send a message
 */
export const sendMessage = async (data: {
  conversation_id: string;
  message: string;
  sender_name: string;
}) => {
  try {
    console.log('📤 Sending message');
    
    const { data: message, error } = await supabase
      .from('chat_messages')
      .insert([{
        conversation_id: data.conversation_id,
        sender_type: 'user',
        sender_name: data.sender_name,
        message: data.message,
      }])
      .select()
      .single();

    if (error) throw error;

    console.log('✅ Message sent');
    return message;
  } catch (error) {
    console.error('❌ Failed to send message:', error);
    throw error;
  }
};

/**
 * Subscribe to conversation messages
 */
export const subscribeToMessages = (
  conversationId: string,
  callback: (message: ChatMessage) => void
) => {
  console.log('🔔 Subscribing to messages:', conversationId);
  
  const channel = supabase
    .channel(`chat-${conversationId}`)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'chat_messages',
        filter: `conversation_id=eq.${conversationId}`,
      },
      (payload) => {
        console.log('📨 New message:', payload.new);
        callback(payload.new as ChatMessage);
      }
    )
    .subscribe();

  return () => {
    console.log('🔕 Unsubscribing from messages');
    supabase.removeChannel(channel);
  };
};

/**
 * Create a support ticket (offline fallback)
 */
export const createSupportTicket = async (data: {
  user_name: string;
  user_email: string;
  topic: string;
  message: string;
}) => {
  try {
    console.log('🎫 Creating support ticket');
    
    const { data: { user } } = await supabase.auth.getUser();
    
    const { data: ticket, error } = await supabase
      .from('support_tickets')
      .insert([{
        user_id: user?.id || null,
        user_name: data.user_name,
        user_email: data.user_email,
        topic: data.topic,
        message: data.message,
        status: 'open',
        ticket_number: '', // Will be auto-generated by trigger
      } as any])
      .select()
      .single();

    if (error) throw error;

    console.log('✅ Support ticket created:', ticket.ticket_number);
    return ticket;
  } catch (error) {
    console.error('❌ Failed to create support ticket:', error);
    throw error;
  }
};

/**
 * Close a conversation
 */
export const closeConversation = async (conversationId: string) => {
  try {
    const { error } = await supabase
      .from('chat_conversations')
      .update({
        status: 'closed',
        closed_at: new Date().toISOString(),
      })
      .eq('id', conversationId);

    if (error) throw error;

    console.log('✅ Conversation closed');
  } catch (error) {
    console.error('❌ Failed to close conversation:', error);
    throw error;
  }
};
